//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXPRT.MainServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://wcfservice120191208111035.azurewebsites.net/", ConfigurationName="MainServiceReference.MainServiceSoap")]
    public interface MainServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://wcfservice120191208111035.azurewebsites.net/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://wcfservice120191208111035.azurewebsites.net/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<int> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://wcfservice120191208111035.azurewebsites.net/GetReports", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetReports(string identifier, int flag);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://wcfservice120191208111035.azurewebsites.net/GetReports", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetReportsAsync(string identifier, int flag);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://wcfservice120191208111035.azurewebsites.net/Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Insert(string ssn, int manager_id, string type, string reason, string date, decimal price);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://wcfservice120191208111035.azurewebsites.net/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> InsertAsync(string ssn, int manager_id, string type, string reason, string date, decimal price);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://wcfservice120191208111035.azurewebsites.net/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update(int report_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://wcfservice120191208111035.azurewebsites.net/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateAsync(int report_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MainServiceSoapChannel : EXPRT.MainServiceReference.MainServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainServiceSoapClient : System.ServiceModel.ClientBase<EXPRT.MainServiceReference.MainServiceSoap>, EXPRT.MainServiceReference.MainServiceSoap {
        
        public MainServiceSoapClient() {
        }
        
        public MainServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public System.Data.DataSet GetReports(string identifier, int flag) {
            return base.Channel.GetReports(identifier, flag);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetReportsAsync(string identifier, int flag) {
            return base.Channel.GetReportsAsync(identifier, flag);
        }
        
        public bool Insert(string ssn, int manager_id, string type, string reason, string date, decimal price) {
            return base.Channel.Insert(ssn, manager_id, type, reason, date, price);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAsync(string ssn, int manager_id, string type, string reason, string date, decimal price) {
            return base.Channel.InsertAsync(ssn, manager_id, type, reason, date, price);
        }
        
        public int Update(int report_id) {
            return base.Channel.Update(report_id);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(int report_id) {
            return base.Channel.UpdateAsync(report_id);
        }
    }
}
